export type CategoryProduct = {
  name: string;
  price: string;
  imageSrc: string;
  imageAlt: string;
  blurb: string;
  badge: string;
  bgClassName: string;
};

export type CategoryEntry = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  heroTitle: string;
  heroBody: string;
  imageSrc: string;
  imageAlt: string;
  accentClassName: string;
  surfaceClassName: string;
  chipLabel: string;
  stats: string[];
  highlights: string[];
  products: CategoryProduct[];
};

export const categoryCatalog: CategoryEntry[] = [
  {
    slug: "electronics",
    name: "Electronics",
    tagline: "Smart upgrades, work gear, and daily tech essentials.",
    description: "Browse laptops, audio, monitors, and everyday electronics picked for value and reliability.",
    heroTitle: "Electronics that make work and play smoother",
    heroBody: "From desk setups to entertainment upgrades, this category brings together practical devices, clean accessories, and best-value tech picks.",
    imageSrc: "/hero-tech.svg",
    imageAlt: "Electronics category visual",
    accentClassName: "from-sky-500 via-cyan-500 to-slate-900",
    surfaceClassName: "bg-[#edf7ff]",
    chipLabel: "Top tech",
    stats: ["240+ gadgets", "Fast movers", "Everyday essentials"],
    highlights: ["Laptops & monitors", "Audio gear", "Charging accessories"],
    products: [
      {
        name: "Wireless headphones",
        price: "$89",
        imageSrc: "/hero-tech.svg",
        imageAlt: "Wireless headphones visual",
        blurb: "Balanced sound, all-day comfort, and easy Bluetooth pairing.",
        badge: "Best seller",
        bgClassName: "bg-[#eef8ff]",
      },
      {
        name: "Portable SSD",
        price: "$74",
        imageSrc: "/hero-tech.svg",
        imageAlt: "Portable SSD visual",
        blurb: "Fast backup storage for work files, media, and travel use.",
        badge: "Work pick",
        bgClassName: "bg-[#f3f7fb]",
      },
      {
        name: "Mechanical keyboard",
        price: "$59",
        imageSrc: "/hero-tech.svg",
        imageAlt: "Mechanical keyboard visual",
        blurb: "Compact layout with satisfying tactility for long sessions.",
        badge: "Setup essential",
        bgClassName: "bg-[#edf4ff]",
      },
      {
        name: "USB-C hub",
        price: "$35",
        imageSrc: "/hero-tech.svg",
        imageAlt: "USB-C hub visual",
        blurb: "Expand ports instantly for laptops, tablets, and desks.",
        badge: "Utility",
        bgClassName: "bg-[#f6faff]",
      },
    ],
  },
  {
    slug: "diy-tools",
    name: "DIY Tools",
    tagline: "Home fixes, workshop basics, and practical tool kits.",
    description: "Discover drills, hand tools, organizers, and repair essentials for home improvement.",
    heroTitle: "DIY tools for repairs, upgrades, and weekend builds",
    heroBody: "Everything here is selected for usability and repeat use, whether you are handling quick fixes or setting up a home workshop.",
    imageSrc: "/hero-home.svg",
    imageAlt: "DIY tools category visual",
    accentClassName: "from-amber-500 via-orange-500 to-stone-900",
    surfaceClassName: "bg-[#fff6ea]",
    chipLabel: "Home projects",
    stats: ["150+ tools", "Repair-ready", "Budget to pro"],
    highlights: ["Power drills", "Tool kits", "Storage organizers"],
    products: [
      {
        name: "Cordless drill set",
        price: "$109",
        imageSrc: "/hero-home.svg",
        imageAlt: "Cordless drill set visual",
        blurb: "Reliable torque for assembly, fixing, and light woodwork.",
        badge: "Workshop pick",
        bgClassName: "bg-[#fff5e8]",
      },
      {
        name: "Precision screwdriver kit",
        price: "$24",
        imageSrc: "/hero-home.svg",
        imageAlt: "Precision screwdriver kit visual",
        blurb: "Compact repair kit for gadgets, glasses, and switches.",
        badge: "Compact essential",
        bgClassName: "bg-[#fff8ef]",
      },
      {
        name: "Wall mounting set",
        price: "$31",
        imageSrc: "/hero-home.svg",
        imageAlt: "Wall mounting set visual",
        blurb: "Anchors, levels, and fasteners for clean installation jobs.",
        badge: "Starter set",
        bgClassName: "bg-[#fff3e3]",
      },
      {
        name: "Heavy-duty toolbox",
        price: "$42",
        imageSrc: "/hero-home.svg",
        imageAlt: "Heavy-duty toolbox visual",
        blurb: "Structured storage for tools, bits, and repair supplies.",
        badge: "Organizer",
        bgClassName: "bg-[#fff7ee]",
      },
    ],
  },
  {
    slug: "mens-wear",
    name: "Men Wear",
    tagline: "Daily basics, workwear staples, and clean weekend fits.",
    description: "Shop shirts, denim, outerwear, and wardrobe basics built for comfort and style.",
    heroTitle: "Men wear with a clean, easy, everyday fit",
    heroBody: "This edit focuses on wearable staples that transition well between work, commute, and casual plans without feeling over-styled.",
    imageSrc: "/hero-travel.svg",
    imageAlt: "Men wear category visual",
    accentClassName: "from-slate-500 via-zinc-600 to-slate-900",
    surfaceClassName: "bg-[#f3f4f6]",
    chipLabel: "Wardrobe core",
    stats: ["180+ styles", "Easy layers", "Daily basics"],
    highlights: ["Shirts & tees", "Denim", "Light jackets"],
    products: [
      {
        name: "Classic oxford shirt",
        price: "$29",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Classic oxford shirt visual",
        blurb: "Crisp structure with soft cotton comfort for everyday wear.",
        badge: "Office casual",
        bgClassName: "bg-[#f5f5f5]",
      },
      {
        name: "Straight-fit denim",
        price: "$39",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Straight-fit denim visual",
        blurb: "A versatile pair that works with sneakers, boots, or loafers.",
        badge: "Most versatile",
        bgClassName: "bg-[#f1f3f5]",
      },
      {
        name: "Everyday polo",
        price: "$22",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Everyday polo visual",
        blurb: "Easy-to-style staple for warmer days and smart-casual dressing.",
        badge: "Easy pick",
        bgClassName: "bg-[#f7f7f8]",
      },
      {
        name: "Utility overshirt",
        price: "$44",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Utility overshirt visual",
        blurb: "A lightweight layering piece with practical pockets and structure.",
        badge: "Layering favorite",
        bgClassName: "bg-[#f4f5f6]",
      },
    ],
  },
  {
    slug: "girls-wear",
    name: "Girls Wear",
    tagline: "Fresh colors, easy comfort, and playful everyday style.",
    description: "Explore dresses, co-ords, tops, and everyday essentials with expressive details.",
    heroTitle: "Girls wear with playful detail and all-day comfort",
    heroBody: "From after-school pieces to weekend looks, these picks focus on soft fabrics, bright styling, and easy movement.",
    imageSrc: "/hero-home.svg",
    imageAlt: "Girls wear category visual",
    accentClassName: "from-rose-400 via-pink-400 to-fuchsia-700",
    surfaceClassName: "bg-[#fff1f6]",
    chipLabel: "New looks",
    stats: ["160+ styles", "Bright palettes", "Soft fabrics"],
    highlights: ["Dresses", "Tops & sets", "Seasonal picks"],
    products: [
      {
        name: "Printed cotton dress",
        price: "$26",
        imageSrc: "/hero-home.svg",
        imageAlt: "Printed cotton dress visual",
        blurb: "Lightweight and breathable with cheerful color placement.",
        badge: "Weekend favorite",
        bgClassName: "bg-[#fff2f7]",
      },
      {
        name: "Ruffle sleeve top",
        price: "$18",
        imageSrc: "/hero-home.svg",
        imageAlt: "Ruffle sleeve top visual",
        blurb: "Soft, easy to pair, and finished with a playful silhouette.",
        badge: "Easy styling",
        bgClassName: "bg-[#fff6fa]",
      },
      {
        name: "Co-ord lounge set",
        price: "$31",
        imageSrc: "/hero-home.svg",
        imageAlt: "Co-ord lounge set visual",
        blurb: "Relaxed comfort for school breaks, outings, and travel days.",
        badge: "Comfort pick",
        bgClassName: "bg-[#fff3f8]",
      },
      {
        name: "Light knit cardigan",
        price: "$24",
        imageSrc: "/hero-home.svg",
        imageAlt: "Light knit cardigan visual",
        blurb: "A simple layer to throw on through changing weather.",
        badge: "Layering",
        bgClassName: "bg-[#fff8fb]",
      },
    ],
  },
  {
    slug: "gadgets",
    name: "Gadgets",
    tagline: "Portable picks, smart helpers, and handy modern extras.",
    description: "Find travel tech, desk gadgets, portable chargers, and clever everyday accessories.",
    heroTitle: "Gadgets that make daily routines simpler",
    heroBody: "This section is built around useful, compact products that feel fun to own and practical to use across work, travel, and home.",
    imageSrc: "/hero-tech.svg",
    imageAlt: "Gadgets category visual",
    accentClassName: "from-violet-500 via-indigo-500 to-slate-900",
    surfaceClassName: "bg-[#f3f0ff]",
    chipLabel: "Smart extras",
    stats: ["130+ gadgets", "Portable picks", "Giftable items"],
    highlights: ["Smart accessories", "Portable power", "Desk gadgets"],
    products: [
      {
        name: "Magnetic power bank",
        price: "$41",
        imageSrc: "/hero-tech.svg",
        imageAlt: "Magnetic power bank visual",
        blurb: "Pocket-friendly charging with a cable-light setup.",
        badge: "Travel ready",
        bgClassName: "bg-[#f4f1ff]",
      },
      {
        name: "Mini desk fan",
        price: "$19",
        imageSrc: "/hero-tech.svg",
        imageAlt: "Mini desk fan visual",
        blurb: "Quiet airflow for warmer work sessions and small spaces.",
        badge: "Desk comfort",
        bgClassName: "bg-[#f7f5ff]",
      },
      {
        name: "Bluetooth tracker",
        price: "$28",
        imageSrc: "/hero-tech.svg",
        imageAlt: "Bluetooth tracker visual",
        blurb: "Keep track of keys, bags, and essentials without the usual hassle.",
        badge: "Daily utility",
        bgClassName: "bg-[#f3f0ff]",
      },
      {
        name: "Smart lamp speaker",
        price: "$63",
        imageSrc: "/hero-tech.svg",
        imageAlt: "Smart lamp speaker visual",
        blurb: "Ambient lighting combined with compact wireless audio.",
        badge: "Hybrid favorite",
        bgClassName: "bg-[#f6f3ff]",
      },
    ],
  },
  {
    slug: "furniture",
    name: "Furniture",
    tagline: "Warm textures, practical comfort, and space-shaping staples.",
    description: "Browse seating, tables, storage pieces, and compact furniture for modern homes.",
    heroTitle: "Furniture that brings comfort and character together",
    heroBody: "From compact apartment pieces to living room anchors, this category focuses on function, finish, and a lived-in sense of style.",
    imageSrc: "/hero-home.svg",
    imageAlt: "Furniture category visual",
    accentClassName: "from-lime-500 via-emerald-500 to-stone-900",
    surfaceClassName: "bg-[#eff5e7]",
    chipLabel: "Home favorite",
    stats: ["210+ pieces", "Living essentials", "Small-space friendly"],
    highlights: ["Sofas", "Accent chairs", "Storage furniture"],
    products: [
      {
        name: "Soft lounge sofa",
        price: "$249",
        imageSrc: "/hero-home.svg",
        imageAlt: "Soft lounge sofa visual",
        blurb: "A grounding centerpiece with a calm color tone and relaxed profile.",
        badge: "Living room",
        bgClassName: "bg-[#f0f6ea]",
      },
      {
        name: "Accent side chair",
        price: "$86",
        imageSrc: "/hero-home.svg",
        imageAlt: "Accent side chair visual",
        blurb: "Compact seating with enough personality to lift a corner.",
        badge: "Statement seat",
        bgClassName: "bg-[#f5f8f0]",
      },
      {
        name: "Open shelf unit",
        price: "$97",
        imageSrc: "/hero-home.svg",
        imageAlt: "Open shelf unit visual",
        blurb: "Display books, decor, and daily-use pieces without clutter.",
        badge: "Storage",
        bgClassName: "bg-[#eef5e5]",
      },
      {
        name: "Round side table",
        price: "$54",
        imageSrc: "/hero-home.svg",
        imageAlt: "Round side table visual",
        blurb: "A simple companion table for seating areas and bedside use.",
        badge: "Flexible use",
        bgClassName: "bg-[#f4f7ef]",
      },
    ],
  },
  {
    slug: "kidswear",
    name: "Kidswear",
    tagline: "Soft fabrics, durable basics, and playful all-day outfits.",
    description: "Shop easy-wear sets, tees, joggers, and seasonal layers designed for movement.",
    heroTitle: "Kidswear made for movement, comfort, and repeat wear",
    heroBody: "These picks are designed around real daily routines, with soft textures, easy care, and playful energy without sacrificing practicality.",
    imageSrc: "/hero-travel.svg",
    imageAlt: "Kidswear category visual",
    accentClassName: "from-yellow-400 via-orange-400 to-rose-600",
    surfaceClassName: "bg-[#fff6e9]",
    chipLabel: "Family picks",
    stats: ["170+ styles", "Everyday comfort", "School-ready"],
    highlights: ["T-shirts", "Joggers", "Matching sets"],
    products: [
      {
        name: "Graphic tee pack",
        price: "$17",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Graphic tee pack visual",
        blurb: "Soft cotton basics that keep rotation simple through the week.",
        badge: "Daily basics",
        bgClassName: "bg-[#fff7ee]",
      },
      {
        name: "Jogger set",
        price: "$28",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Jogger set visual",
        blurb: "Comfort-first coordinated set for school, play, and travel.",
        badge: "Comfort",
        bgClassName: "bg-[#fff5e8]",
      },
      {
        name: "Light hoodie",
        price: "$21",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Light hoodie visual",
        blurb: "An easy layering piece for breezy mornings and evening outings.",
        badge: "Layering favorite",
        bgClassName: "bg-[#fff8f0]",
      },
      {
        name: "Play shorts duo",
        price: "$16",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Play shorts duo visual",
        blurb: "Flexible everyday bottoms for active routines and warmer weather.",
        badge: "Value pack",
        bgClassName: "bg-[#fff6ea]",
      },
    ],
  },
  {
    slug: "bags",
    name: "Bags",
    tagline: "Commute-ready carry, travel options, and versatile daily packs.",
    description: "Explore backpacks, totes, slings, and luggage built for movement and organization.",
    heroTitle: "Bags that keep everyday carry organized and stylish",
    heroBody: "This category balances durable materials, thoughtful compartments, and designs that work across office, campus, and travel use.",
    imageSrc: "/hero-travel.svg",
    imageAlt: "Bags category visual",
    accentClassName: "from-emerald-500 via-teal-500 to-cyan-900",
    surfaceClassName: "bg-[#eaf8f6]",
    chipLabel: "Travel-ready",
    stats: ["140+ carry picks", "Commute-focused", "Weekend travel"],
    highlights: ["Backpacks", "Slings", "Totes & duffels"],
    products: [
      {
        name: "Urban commute backpack",
        price: "$47",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Urban commute backpack visual",
        blurb: "Laptop-friendly structure with compartments for daily use.",
        badge: "Best seller",
        bgClassName: "bg-[#eefaf8]",
      },
      {
        name: "Crossbody sling",
        price: "$22",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Crossbody sling visual",
        blurb: "Compact carry for essentials when you want to move light.",
        badge: "Minimal carry",
        bgClassName: "bg-[#f2fbfa]",
      },
      {
        name: "Weekender duffel",
        price: "$58",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Weekender duffel visual",
        blurb: "Spacious enough for short trips without feeling bulky.",
        badge: "Short trips",
        bgClassName: "bg-[#edf9f7]",
      },
      {
        name: "Structured tote",
        price: "$34",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Structured tote visual",
        blurb: "A cleaner silhouette for errands, work, and casual plans.",
        badge: "Everyday carry",
        bgClassName: "bg-[#f4fcfb]",
      },
    ],
  },
  {
    slug: "groceries",
    name: "Groceries",
    tagline: "Pantry staples, quick snacks, and everyday kitchen basics.",
    description: "Shop grains, breakfast items, snacks, and home pantry must-haves.",
    heroTitle: "Groceries that keep the pantry practical and well stocked",
    heroBody: "Built around daily use and smart replenishment, this category keeps food staples, snacks, and household consumables easy to browse and refill.",
    imageSrc: "/hero-home.svg",
    imageAlt: "Groceries category visual",
    accentClassName: "from-orange-400 via-amber-400 to-lime-700",
    surfaceClassName: "bg-[#fff7e8]",
    chipLabel: "Daily pantry",
    stats: ["300+ staples", "Quick refills", "Household basics"],
    highlights: ["Breakfast picks", "Cooking staples", "Snacks & beverages"],
    products: [
      {
        name: "Mixed dry fruits pack",
        price: "$14",
        imageSrc: "/hero-home.svg",
        imageAlt: "Mixed dry fruits pack visual",
        blurb: "A pantry-friendly snack with balanced sweetness and crunch.",
        badge: "Healthy snack",
        bgClassName: "bg-[#fff7ec]",
      },
      {
        name: "Cold brew bottles",
        price: "$11",
        imageSrc: "/hero-home.svg",
        imageAlt: "Cold brew bottles visual",
        blurb: "Grab-and-go coffee for busy mornings and afternoon resets.",
        badge: "Quick pick",
        bgClassName: "bg-[#fff9f1]",
      },
      {
        name: "Cooking essentials bundle",
        price: "$27",
        imageSrc: "/hero-home.svg",
        imageAlt: "Cooking essentials bundle visual",
        blurb: "A practical mix of oil, grains, and staple ingredients.",
        badge: "Bundle value",
        bgClassName: "bg-[#fff5e7]",
      },
      {
        name: "Breakfast cereal duo",
        price: "$9",
        imageSrc: "/hero-home.svg",
        imageAlt: "Breakfast cereal duo visual",
        blurb: "Everyday breakfast convenience with family-friendly variety.",
        badge: "Morning staple",
        bgClassName: "bg-[#fffaf4]",
      },
    ],
  },
  {
    slug: "kitchen-wear",
    name: "Kitchen Wear",
    tagline: "Cookware, serving pieces, and prep-friendly kitchen tools.",
    description: "Discover pans, storage, utensils, and table-ready pieces for daily cooking.",
    heroTitle: "Kitchen wear that keeps cooking smooth and organized",
    heroBody: "This category brings together utility-first cookware, prep tools, and storage solutions that make daily kitchen routines feel lighter.",
    imageSrc: "/hero-home.svg",
    imageAlt: "Kitchen wear category visual",
    accentClassName: "from-red-400 via-orange-400 to-stone-900",
    surfaceClassName: "bg-[#fff1eb]",
    chipLabel: "Cook & serve",
    stats: ["190+ tools", "Meal prep ready", "Storage-friendly"],
    highlights: ["Cookware", "Utensils", "Storage containers"],
    products: [
      {
        name: "Non-stick pan set",
        price: "$49",
        imageSrc: "/hero-home.svg",
        imageAlt: "Non-stick pan set visual",
        blurb: "An everyday pan duo suited for quick meals and easy cleanup.",
        badge: "Kitchen staple",
        bgClassName: "bg-[#fff2ec]",
      },
      {
        name: "Glass storage set",
        price: "$29",
        imageSrc: "/hero-home.svg",
        imageAlt: "Glass storage set visual",
        blurb: "Clean storage for leftovers, prep, and pantry organization.",
        badge: "Meal prep",
        bgClassName: "bg-[#fff6f2]",
      },
      {
        name: "Knife and board combo",
        price: "$34",
        imageSrc: "/hero-home.svg",
        imageAlt: "Knife and board combo visual",
        blurb: "A basic prep pairing designed for daily convenience.",
        badge: "Prep essential",
        bgClassName: "bg-[#fff3ee]",
      },
      {
        name: "Serving bowl set",
        price: "$26",
        imageSrc: "/hero-home.svg",
        imageAlt: "Serving bowl set visual",
        blurb: "Durable pieces that move easily from kitchen to table.",
        badge: "Dining ready",
        bgClassName: "bg-[#fff8f5]",
      },
    ],
  },
  {
    slug: "beauty-care",
    name: "Beauty Care",
    tagline: "Everyday skincare, grooming, and simple self-care picks.",
    description: "Shop cleansers, body care, grooming tools, and daily beauty essentials.",
    heroTitle: "Beauty care that fits into a calm daily routine",
    heroBody: "This collection focuses on practical skincare, grooming, and self-care products that feel easy to maintain and pleasant to repeat.",
    imageSrc: "/hero-home.svg",
    imageAlt: "Beauty care category visual",
    accentClassName: "from-pink-300 via-rose-300 to-orange-500",
    surfaceClassName: "bg-[#fff3f4]",
    chipLabel: "Daily care",
    stats: ["120+ care picks", "Routine staples", "Giftable edits"],
    highlights: ["Skincare", "Body care", "Grooming tools"],
    products: [
      {
        name: "Hydration skincare duo",
        price: "$23",
        imageSrc: "/hero-home.svg",
        imageAlt: "Hydration skincare duo visual",
        blurb: "Clean, everyday hydration for simple morning and night use.",
        badge: "Routine favorite",
        bgClassName: "bg-[#fff4f6]",
      },
      {
        name: "Body care set",
        price: "$19",
        imageSrc: "/hero-home.svg",
        imageAlt: "Body care set visual",
        blurb: "Balanced wash and lotion pair for daily care that feels easy.",
        badge: "Self-care",
        bgClassName: "bg-[#fff7f8]",
      },
      {
        name: "Travel grooming kit",
        price: "$17",
        imageSrc: "/hero-home.svg",
        imageAlt: "Travel grooming kit visual",
        blurb: "Compact grooming essentials for short trips and busy weeks.",
        badge: "Travel ready",
        bgClassName: "bg-[#fff3f5]",
      },
      {
        name: "Facial roller set",
        price: "$14",
        imageSrc: "/hero-home.svg",
        imageAlt: "Facial roller set visual",
        blurb: "A lightweight add-on for a more intentional evening routine.",
        badge: "Wellness add-on",
        bgClassName: "bg-[#fff8f9]",
      },
    ],
  },
  {
    slug: "sports-fitness",
    name: "Sports & Fitness",
    tagline: "Movement essentials, training basics, and wellness tools.",
    description: "Explore bottles, mats, resistance gear, and active lifestyle products.",
    heroTitle: "Sports and fitness picks that support daily movement",
    heroBody: "Whether you are just starting or topping up an existing routine, these products focus on practical support and repeatable use.",
    imageSrc: "/hero-travel.svg",
    imageAlt: "Sports and fitness category visual",
    accentClassName: "from-emerald-400 via-lime-400 to-slate-900",
    surfaceClassName: "bg-[#eefbea]",
    chipLabel: "Active living",
    stats: ["110+ fitness picks", "Home workouts", "Daily wellness"],
    highlights: ["Yoga & mats", "Bottles", "Training accessories"],
    products: [
      {
        name: "Yoga mat",
        price: "$27",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Yoga mat visual",
        blurb: "Comfortable grip and easy roll-up storage for home sessions.",
        badge: "Home workout",
        bgClassName: "bg-[#f1fcea]",
      },
      {
        name: "Resistance band set",
        price: "$16",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Resistance band set visual",
        blurb: "Compact training support for strength, warmups, and mobility.",
        badge: "Compact training",
        bgClassName: "bg-[#f5fdef]",
      },
      {
        name: "Insulated sports bottle",
        price: "$18",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Insulated sports bottle visual",
        blurb: "Keeps hydration within reach for workouts and commutes alike.",
        badge: "Hydration",
        bgClassName: "bg-[#eefbe8]",
      },
      {
        name: "Recovery foam roller",
        price: "$24",
        imageSrc: "/hero-travel.svg",
        imageAlt: "Recovery foam roller visual",
        blurb: "A simple recovery tool for stretching and post-session release.",
        badge: "Recovery tool",
        bgClassName: "bg-[#f3fdef]",
      },
    ],
  },
];

export function getCategoryBySlug(slug: string) {
  return categoryCatalog.find((category) => category.slug === slug);
}
